### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Comment by DouglasRaillard** [comment]
Hi Ralic,

As shown in the shebang, this lib is already developed for Python 3 only. 2to3 script seems to have made the following changes:
1) Adding useless parenthesis around arguments in printf
2) Adding useless list() around <dict>.items() calls

Did you have any issue running this code on a specific Python 3 version ? From the top of my head, it may require > 3.2 for some features in functools module (need to check for the details).

Also, the .bak files should not be included in the pull requests.

Thanks,
Douglas

**Comment by ralic** [comment]
Hello Douglas, I tested it in macOS, using python3.6. In those examples, I found test4/test5 may need further check. Please see if you may help on this. It's ok to close this request and you may just take those you think worth to change. Thanks !

**Comment by DouglasRaillard** [comment]
I pushed a fix for the FunCall constructor that made some example to fail. Other examples may be broken by API change, which will be fixed the day I resume the work on this library. 
The main changes that have been "in frozen progress" for the last years are:
- Refactor the FunParam to make them more variable-like
- Split the code further between core.py and C.py
- Add some classes to handle source files and header for the common cases.

If you intend to work on the inner parts of the library, let me know so this does not clash with the current work. For the moment, I'll close this PR as it does not contain any relevant change.

I strongly suggest refraining from pushing automated changes to 377 repositories in one day as this is clearly low quality spam and loss of time for all the people involved. 

Thanks,
Douglas

**Comment by DouglasRaillard** [comment]
Note: I rebased the master branch and pushed forcefully to get rid of a "WIP" commit message that was annoying with my pre-push hook. As you have the only fork for now, the impact is limited. As a result, you'll need to rebase your work on top of the new master branch.

**Pull request closed without merging**
